## Session 3: Pandas Fundamentals
## DataFrames, Reading/Writing Data & Basic Operations
**Modern Data Engineering Course** — Week 2 Session 3 
**Instructors:** Ameer

## 1. Installing & Importing Pandas

In [398]:
# Install pandas (run once if not already installed)
# !pip3 install pandas numpy

import pandas as pd
import numpy as np

print(f"Pandas version: {pd.__version__}")
print(f"NumPy version: {np.__version__}")

Pandas version: 2.2.3
NumPy version: 2.4.4

## 2. Series — The Building Block

A **Series** is a single column of data — like one column in a spreadsheet.

In [399]:
# Creating a Series from a list
prices = pd.Series([29.99, 49.99, 19.99])
print(prices)
print()
print(f"Type: {type(prices)}")

0    29.99
1    49.99
2    19.99
dtype: float64

Type: <class 'pandas.core.series.Series'>

In [400]:
# Series with custom index
prices = pd.Series(
    [29.99, 49.99, 19.99],
    index=["shirt", "pants", "cap"]
)
print(prices)

shirt    29.99
pants    49.99
cap      19.99
dtype: float64

In [401]:
# Key attributes
print(f"Values: {prices.values}")
print(f"Index:  {prices.index.tolist()}")
print(f"Dtype:  {prices.dtype}")
print(f"Size:   {prices.size}")

Values: [29.99 49.99 19.99]
Index:  ['shirt', 'pants', 'cap']
Dtype:  float64
Size:   3

## 3. DataFrame — The Star of the Show

A **DataFrame** is a 2D table — like a full spreadsheet or database table.  
Think of it as **multiple Series** sharing the same index.

In [402]:
# Creating a DataFrame from a dictionary
data = {
    "product": ["Laptop", "Phone", "Tablet"],
    "price":   [999.99, 699.99, 399.99],
    "stock":   [50, 150, 80]
}

df = pd.DataFrame(data)
print(df)

  product   price  stock
0  Laptop  999.99     50
1   Phone  699.99    150
2  Tablet  399.99     80

In [403]:
# DataFrame with custom index
df = pd.DataFrame(data, index=["P001", "P002", "P003"])
print(df)

     product   price  stock
P001  Laptop  999.99     50
P002   Phone  699.99    150
P003  Tablet  399.99     80

## 4. Exploring Your DataFrame

**Rule #1:** Always explore your data before doing anything else!

In [404]:
# Let's create a bigger dataset to explore
orders = {
    "order_id":  [101, 102, 103, 104, 105, 106, 107, 108],
    "customer":  ["Alice", "Bob", "Alice", "Charlie", "Bob", "Dave", "Alice", "Charlie"],
    "product":   ["Laptop", "Phone", "Tablet", "Laptop", "Phone", "Mouse", "Keyboard", "Monitor"],
    "amount":    [999.99, 699.99, 399.99, 999.99, 699.99, 29.99, 79.99, 549.99],
    "city":      ["Dhaka", "Chittagong", "Dhaka", "Sylhet", "Dhaka", "Chittagong", "Sylhet", "Dhaka"],
}

df = pd.DataFrame(orders)
print(df)

   order_id customer   product  amount        city
0       101    Alice    Laptop  999.99       Dhaka
1       102      Bob     Phone  699.99  Chittagong
2       103    Alice    Tablet  399.99       Dhaka
3       104  Charlie    Laptop  999.99      Sylhet
4       105      Bob     Phone  699.99       Dhaka
5       106     Dave     Mouse   29.99  Chittagong
6       107    Alice  Keyboard   79.99      Sylhet
7       108  Charlie   Monitor  549.99       Dhaka

In [405]:
# Peek at the top rows
df.head()

   order_id customer product  amount        city
0       101    Alice  Laptop  999.99       Dhaka
1       102      Bob   Phone  699.99  Chittagong
2       103    Alice  Tablet  399.99       Dhaka
3       104  Charlie  Laptop  999.99      Sylhet
4       105      Bob   Phone  699.99       Dhaka

In [406]:
# Peek at the bottom rows
df.tail()

   order_id customer   product  amount        city
3       104  Charlie    Laptop  999.99      Sylhet
4       105      Bob     Phone  699.99       Dhaka
5       106     Dave     Mouse   29.99  Chittagong
6       107    Alice  Keyboard   79.99      Sylhet
7       108  Charlie   Monitor  549.99       Dhaka

In [407]:
# Shape: (rows, columns)
print(f"Shape: {df.shape}")
print(f"Rows:  {df.shape[0]}")
print(f"Cols:  {df.shape[1]}")

Shape: (8, 5)
Rows:  8
Cols:  5

In [408]:
# Column info — types, null counts, memory
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  8 non-null      int64
 1   customer  8 non-null      object
 2   product   8 non-null      object
 3   amount    8 non-null      float64
 4   city      8 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 452.0+ bytes

In [409]:
# Statistics for numeric columns
df.describe()

        order_id      amount
count    8.00000    8.000000
mean   104.50000  557.490000
std      2.44949  370.973622
min    101.00000   29.990000
25%    102.75000  319.990000
50%    104.50000  624.990000
75%    106.25000  774.990000
max    108.00000  999.990000

In [410]:
# Column names
print(df.columns.tolist())

['order_id', 'customer', 'product', 'amount', 'city']

In [411]:
# Data types
print(df.dtypes)

order_id      int64
customer     object
product      object
amount      float64
city         object
dtype: object

## 5. Reading CSV Files

CSV (Comma-Separated Values) — the most common data format you'll encounter.

In [412]:
# First, let's create a sample CSV to work with
sample_data = {
    "order_id":  [201, 202, 203, 204, 205],
    "customer":  ["Rahim", "Karim", "Fatima", "Ayesha", "Rahim"],
    "product":   ["Rice (50kg)", "Laptop", "Saree", "Phone", "Fish (10kg)"],
    "amount":    [2500.00, 75000.00, 3500.00, 45000.00, 5000.00],
    "city":      ["Dhaka", "Chittagong", "Sylhet", "Dhaka", "Dhaka"],
}

sample_df = pd.DataFrame(sample_data)
sample_df.to_csv("sales_data.csv", index=False)
print("✅ sales_data.csv created!")
print(sample_df)

✅ sales_data.csv created!
   order_id customer      product   amount        city
0       201    Rahim  Rice (50kg)   2500.0       Dhaka
1       202    Karim       Laptop  75000.0  Chittagong
2       203   Fatima        Saree   3500.0      Sylhet
3       204   Ayesha        Phone  45000.0       Dhaka
4       205    Rahim  Fish (10kg)   5000.0       Dhaka

In [413]:
# Read the CSV back
df_csv = pd.read_csv("sales_data.csv")
print(df_csv)
print()
print(f"Shape: {df_csv.shape}")

   order_id customer      product   amount        city
0       201    Rahim  Rice (50kg)   2500.0       Dhaka
1       202    Karim       Laptop  75000.0  Chittagong
2       203   Fatima        Saree   3500.0      Sylhet
3       204   Ayesha        Phone  45000.0       Dhaka
4       205    Rahim  Fish (10kg)   5000.0       Dhaka

Shape: (5, 5)

In [414]:
# Useful read_csv parameters
df = pd.read_csv("sales_data.csv")
# df = pd.read_csv("sales_data.csv", header=None)       # No header row
# df = pd.read_csv("sales_data.csv", usecols=["product"])  # Specific columns
# df = pd.read_csv("sales_data.csv", usecols=["customer", "amount"]) # Specific multi columns
# df = pd.read_csv("sales_data.csv", nrows=2)          # First N rows
print(df)

   order_id customer      product   amount        city
0       201    Rahim  Rice (50kg)   2500.0       Dhaka
1       202    Karim       Laptop  75000.0  Chittagong
2       203   Fatima        Saree   3500.0      Sylhet
3       204   Ayesha        Phone  45000.0       Dhaka
4       205    Rahim  Fish (10kg)   5000.0       Dhaka

## 6. Reading Excel & JSON

In [415]:
# Reading & Writing CSV files
# CSV
sample_df.to_csv("output.csv", index=False)
print("✅ Saved as CSV")

✅ Saved as CSV

In [416]:
df_csv = pd.read_csv("output.csv")
print(df_csv)

   order_id customer      product   amount        city
0       201    Rahim  Rice (50kg)   2500.0       Dhaka
1       202    Karim       Laptop  75000.0  Chittagong
2       203   Fatima        Saree   3500.0      Sylhet
3       204   Ayesha        Phone  45000.0       Dhaka
4       205    Rahim  Fish (10kg)   5000.0       Dhaka

In [417]:
# Reading & Writing Excel files (requires openpyxl)
# !pip install openpyxl

# Create a sample Excel file first
sample_df.to_excel("sales_data.xlsx", index=False, sheet_name="Orders")
print("✅ sales_data.xlsx created!")

✅ sales_data.xlsx created!

In [418]:
# Read it back
df_excel = pd.read_excel("sales_data.xlsx", sheet_name="Orders")
print(df_excel)

   order_id customer      product  amount        city
0       201    Rahim  Rice (50kg)    2500       Dhaka
1       202    Karim       Laptop   75000  Chittagong
2       203   Fatima        Saree    3500      Sylhet
3       204   Ayesha        Phone   45000       Dhaka
4       205    Rahim  Fish (10kg)    5000       Dhaka

In [419]:
# Writing & Reading JSON files
# Create a sample JSON file
sample_df.to_json("sales_data.json", orient="records", indent=2)
print("✅ sales_data.json created!")

✅ sales_data.json created!

In [420]:
# Read it back
df_json = pd.read_json("sales_data.json")
print(df_json)

   order_id customer      product  amount        city
0       201    Rahim  Rice (50kg)    2500       Dhaka
1       202    Karim       Laptop   75000  Chittagong
2       203   Fatima        Saree    3500      Sylhet
3       204   Ayesha        Phone   45000       Dhaka
4       205    Rahim  Fish (10kg)    5000       Dhaka

In [421]:
# Parquet (preferred in data engineering — columnar, compressed, fast!)
sample_df.to_parquet("sales_data.parquet")
print("✅ Saved as Parquet")

✅ Saved as Parquet

In [422]:
# Read it back
df_parquet = pd.read_parquet("sales_data.parquet")
print(df_parquet)

   order_id customer      product   amount        city
0       201    Rahim  Rice (50kg)   2500.0       Dhaka
1       202    Karim       Laptop  75000.0  Chittagong
2       203   Fatima        Saree   3500.0      Sylhet
3       204   Ayesha        Phone  45000.0       Dhaka
4       205    Rahim  Fish (10kg)   5000.0       Dhaka

In [423]:
import os

# Small dataset
small = pd.DataFrame({"name": ["Rahim"] * 10, "amount": [100] * 10})
small.to_csv("small.csv", index=False)
small.to_parquet("small.parquet")
print(f"Small CSV:     {os.path.getsize('small.csv'):,} bytes")
print(f"Small Parquet: {os.path.getsize('small.parquet'):,} bytes")

print()

# Large dataset — this is where Parquet shines
large = pd.DataFrame({"name": ["Rahim"] * 100_000, "amount": [100] * 100_000})
large.to_csv("large.csv", index=False)
large.to_parquet("large.parquet")
print(f"Large CSV:     {os.path.getsize('large.csv'):,} bytes")
print(f"Large Parquet: {os.path.getsize('large.parquet'):,} bytes")

Small CSV:     112 bytes
Small Parquet: 2,229 bytes

Large CSV:     1,000,012 bytes
Large Parquet: 2,269 bytes

---
## ☕ Break Time! (10 minutes)

Stretch, grab a drink, and come back refreshed!

---

## 7. Selecting Columns

In [424]:
# Recreate our orders DataFrame
orders = {
    "order_id":  [101, 102, 103, 104, 105, 106, 107, 108],
    "customer":  ["Alice", "Bob", "Alice", "Charlie", "Bob", "Dave", "Alice", "Charlie"],
    "product":   ["Laptop", "Phone", "Tablet", "Laptop", "Phone", "Mouse", "Keyboard", "Monitor"],
    "amount":    [999.99, 699.99, 399.99, 999.99, 699.99, 29.99, 79.99, 549.99],
    "city":      ["Dhaka", "Chittagong", "Dhaka", "Sylhet", "Dhaka", "Chittagong", "Sylhet", "Dhaka"],
}
df = pd.DataFrame(orders)

# Single column → returns a Series
print("=== Single Column (Series) ===")
print(df["product"])

=== Single Column (Series) ===
0      Laptop
1       Phone
2      Tablet
3      Laptop
4       Phone
5       Mouse
6    Keyboard
7     Monitor
Name: product, dtype: object

In [425]:
# Multiple columns → returns a DataFrame
print("=== Multiple Columns (DataFrame) ===")
print(df[["customer", "amount"]])

=== Multiple Columns (DataFrame) ===
  customer  amount
0    Alice  999.99
1      Bob  699.99
2    Alice  399.99
3  Charlie  999.99
4      Bob  699.99
5     Dave   29.99
6    Alice   79.99
7  Charlie  549.99

In [426]:
# Using loc — select by label
print("=== loc: rows 0-2, specific columns ===")
print(df.loc[0:2, ["product", "amount"]])

=== loc: rows 0-2, specific columns ===
  product  amount
0  Laptop  999.99
1   Phone  699.99
2  Tablet  399.99

In [427]:
# Using iloc — select by position
print("=== iloc: first 3 rows, columns 1-3 ===")
print(df.iloc[0:3, 0:3])

=== iloc: first 3 rows, columns 1-3 ===
   order_id customer product
0       101    Alice  Laptop
1       102      Bob   Phone
2       103    Alice  Tablet

## 8. Filtering Rows

Ask questions of your data — Pandas gives you the answers.

In [428]:
# Single condition: orders over ৳500
expensive = df[df["amount"] > 500]
print("=== Orders over ৳500 ===")
print(expensive)

=== Orders over ৳500 ===
   order_id customer  product  amount        city
0       101    Alice   Laptop  999.99       Dhaka
1       102      Bob    Phone  699.99  Chittagong
3       104  Charlie   Laptop  999.99      Sylhet
4       105      Bob    Phone  699.99       Dhaka
7       108  Charlie  Monitor  549.99       Dhaka

In [429]:
# Multiple conditions with AND (&)
# Alice's orders over ৳500
alice_expensive = df[(df["amount"] > 500) & (df["customer"] == "Charlie")]
print("=== Alice's orders over ৳500 ===")
print(alice_expensive)

=== Alice's orders over ৳500 ===
   order_id customer  product  amount    city
3       104  Charlie   Laptop  999.99  Sylhet
7       108  Charlie  Monitor  549.99   Dhaka

In [430]:
# Multiple conditions with OR (|)
# Laptops or Phones
devices = df[(df["product"] == "Laptop") | (df["product"] == "Phone") ]
print("=== Laptops or Phones ===")
print(devices)

=== Laptops or Phones ===
   order_id customer product  amount        city
0       101    Alice  Laptop  999.99       Dhaka
1       102      Bob   Phone  699.99  Chittagong
3       104  Charlie  Laptop  999.99      Sylhet
4       105      Bob   Phone  699.99       Dhaka

In [431]:
# Using isin() for multiple values — cleaner than multiple OR
devices = df[df["product"].isin(["Laptop", "Phone", "Tablet"])]
print("=== Devices (using isin) ===")
print(devices)

=== Devices (using isin) ===
   order_id customer product  amount        city
0       101    Alice  Laptop  999.99       Dhaka
1       102      Bob   Phone  699.99  Chittagong
2       103    Alice  Tablet  399.99       Dhaka
3       104  Charlie  Laptop  999.99      Sylhet
4       105      Bob   Phone  699.99       Dhaka

In [432]:
# Filter by city
dhaka_orders = df[df["city"] == "Dhaka"]
print(f"=== Orders from Dhaka ({len(dhaka_orders)} orders) ===")
print(dhaka_orders)

=== Orders from Dhaka (4 orders) ===
   order_id customer  product  amount   city
0       101    Alice   Laptop  999.99  Dhaka
2       103    Alice   Tablet  399.99  Dhaka
4       105      Bob    Phone  699.99  Dhaka
7       108  Charlie  Monitor  549.99  Dhaka

## 9. Sorting Data

In [433]:
# Sort by amount — ascending (default)
print("=== Sorted by amount (ascending) ===")
print(df.sort_values("amount"))

=== Sorted by amount (ascending) ===
   order_id customer   product  amount        city
5       106     Dave     Mouse   29.99  Chittagong
6       107    Alice  Keyboard   79.99      Sylhet
2       103    Alice    Tablet  399.99       Dhaka
7       108  Charlie   Monitor  549.99       Dhaka
1       102      Bob     Phone  699.99  Chittagong
4       105      Bob     Phone  699.99       Dhaka
0       101    Alice    Laptop  999.99       Dhaka
3       104  Charlie    Laptop  999.99      Sylhet

In [434]:
# Sort by amount — descending
print("=== Sorted by amount (descending) ===")
print(df.sort_values("amount", ascending=False))

=== Sorted by amount (descending) ===
   order_id customer   product  amount        city
0       101    Alice    Laptop  999.99       Dhaka
3       104  Charlie    Laptop  999.99      Sylhet
1       102      Bob     Phone  699.99  Chittagong
4       105      Bob     Phone  699.99       Dhaka
7       108  Charlie   Monitor  549.99       Dhaka
2       103    Alice    Tablet  399.99       Dhaka
6       107    Alice  Keyboard   79.99      Sylhet
5       106     Dave     Mouse   29.99  Chittagong

In [435]:
# Sort by multiple columns
print("=== Sorted by customer, then amount (desc) ===")
print(df.sort_values(["amount", "customer"], ascending=[True, False]))

=== Sorted by customer, then amount (desc) ===
   order_id customer   product  amount        city
5       106     Dave     Mouse   29.99  Chittagong
6       107    Alice  Keyboard   79.99      Sylhet
2       103    Alice    Tablet  399.99       Dhaka
7       108  Charlie   Monitor  549.99       Dhaka
1       102      Bob     Phone  699.99  Chittagong
4       105      Bob     Phone  699.99       Dhaka
3       104  Charlie    Laptop  999.99      Sylhet
0       101    Alice    Laptop  999.99       Dhaka

In [436]:
# Sort and reset index (clean output)
df_sorted = df.sort_values("amount", ascending=True).reset_index(drop=True)
print("=== Sorted with clean index ===")
print(df_sorted)

=== Sorted with clean index ===
   order_id customer   product  amount        city
0       106     Dave     Mouse   29.99  Chittagong
1       107    Alice  Keyboard   79.99      Sylhet
2       103    Alice    Tablet  399.99       Dhaka
3       108  Charlie   Monitor  549.99       Dhaka
4       102      Bob     Phone  699.99  Chittagong
5       105      Bob     Phone  699.99       Dhaka
6       101    Alice    Laptop  999.99       Dhaka
7       104  Charlie    Laptop  999.99      Sylhet

## 10. Adding & Modifying Columns

In [437]:
print(df)

   order_id customer   product  amount        city
0       101    Alice    Laptop  999.99       Dhaka
1       102      Bob     Phone  699.99  Chittagong
2       103    Alice    Tablet  399.99       Dhaka
3       104  Charlie    Laptop  999.99      Sylhet
4       105      Bob     Phone  699.99       Dhaka
5       106     Dave     Mouse   29.99  Chittagong
6       107    Alice  Keyboard   79.99      Sylhet
7       108  Charlie   Monitor  549.99       Dhaka

In [438]:
# Add a new column — tax (5%)
df["tax"] = df["amount"] * 0.05
print("=== Added tax column ===")
print(df)
print(df[["product", "amount", "tax"]].head())

=== Added tax column ===
   order_id customer   product  amount        city      tax
0       101    Alice    Laptop  999.99       Dhaka  49.9995
1       102      Bob     Phone  699.99  Chittagong  34.9995
2       103    Alice    Tablet  399.99       Dhaka  19.9995
3       104  Charlie    Laptop  999.99      Sylhet  49.9995
4       105      Bob     Phone  699.99       Dhaka  34.9995
5       106     Dave     Mouse   29.99  Chittagong   1.4995
6       107    Alice  Keyboard   79.99      Sylhet   3.9995
7       108  Charlie   Monitor  549.99       Dhaka  27.4995
  product  amount      tax
0  Laptop  999.99  49.9995
1   Phone  699.99  34.9995
2  Tablet  399.99  19.9995
3  Laptop  999.99  49.9995
4   Phone  699.99  34.9995

In [439]:
# Column from calculation
df["total"] = df["amount"] + df["tax"]
print("=== Added total column ===")
print(df[["product", "amount", "tax", "total"]].head())

=== Added total column ===
  product  amount      tax      total
0  Laptop  999.99  49.9995  1049.9895
1   Phone  699.99  34.9995   734.9895
2  Tablet  399.99  19.9995   419.9895
3  Laptop  999.99  49.9995  1049.9895
4   Phone  699.99  34.9995   734.9895

In [440]:
# Conditional column using np.where
df["tier"] = np.where(df["amount"] > 500, "Premium", "Standard")
print("=== Added tier column ===")
print(df[["product", "amount", "tier"]])

=== Added tier column ===
    product  amount      tier
0    Laptop  999.99   Premium
1     Phone  699.99   Premium
2    Tablet  399.99  Standard
3    Laptop  999.99   Premium
4     Phone  699.99   Premium
5     Mouse   29.99  Standard
6  Keyboard   79.99  Standard
7   Monitor  549.99   Premium

In [441]:
df["tier"] = "Standard"
print(df["tier"])
df.loc[df["amount"] > 500, "tier"] = "Premium"
print(df)

0    Standard
1    Standard
2    Standard
3    Standard
4    Standard
5    Standard
6    Standard
7    Standard
Name: tier, dtype: object
   order_id customer   product  amount        city      tax      total  \
0       101    Alice    Laptop  999.99       Dhaka  49.9995  1049.9895
1       102      Bob     Phone  699.99  Chittagong  34.9995   734.9895
2       103    Alice    Tablet  399.99       Dhaka  19.9995   419.9895
3       104  Charlie    Laptop  999.99      Sylhet  49.9995  1049.9895
4       105      Bob     Phone  699.99       Dhaka  34.9995   734.9895
5       106     Dave     Mouse   29.99  Chittagong   1.4995    31.4895
6       107    Alice  Keyboard   79.99      Sylhet   3.9995    83.9895
7       108  Charlie   Monitor  549.99       Dhaka  27.4995   577.4895

       tier
0   Premium
1   Premium
2  Standard
3   Premium
4   Premium
5  Standard
6  Standard
7   Premium

In [442]:
# Rename columns
print(df.columns.tolist())
df = df.rename(columns={
    "amount": "order_amount",
    "customer": "customer_name"
})
print("=== Renamed columns ===")
print(df.columns.tolist())

['order_id', 'customer', 'product', 'amount', 'city', 'tax', 'total', 'tier']
=== Renamed columns ===
['order_id', 'customer_name', 'product', 'order_amount', 'city', 'tax', 'total', 'tier']

In [443]:
# Drop a column
df = df.drop(columns=["tax"])
print("=== Dropped tax column ===")
print(df.columns.tolist())

=== Dropped tax column ===
['order_id', 'customer_name', 'product', 'order_amount', 'city', 'total', 'tier']

## 11. Basic Aggregations

In [451]:
# Simple aggregation methods
print(df['order_amount'])
print(df['order_amount'].sort_values())
print(f"Total revenue: ৳{df['order_amount'].sum():,.2f}")
print(f"Average order: ৳{df['order_amount'].mean():,.2f}")
print(f"Median order:  ৳{df['order_amount'].median():,.2f}")
print(f"Min order:     ৳{df['order_amount'].min():,.2f}")
print(f"Max order:     ৳{df['order_amount'].max():,.2f}")
print(f"Unique products: {df['product'].nunique()}")

0    999.99
1    699.99
2    399.99
3    999.99
4    699.99
5     29.99
6     79.99
7    549.99
Name: order_amount, dtype: float64
5     29.99
6     79.99
2    399.99
7    549.99
1    699.99
4    699.99
0    999.99
3    999.99
Name: order_amount, dtype: float64
Total revenue: ৳4,459.92
Average order: ৳557.49
Median order:  ৳624.99
Min order:     ৳29.99
Max order:     ৳999.99
Unique products: 6

In [452]:
# value_counts() — instant frequency table
print("=== Product frequency ===")
print(df["product"].value_counts())
print()
print("=== Customer frequency ===")
print(df["customer_name"].value_counts())

=== Product frequency ===
product
Laptop      2
Phone       2
Tablet      1
Mouse       1
Keyboard    1
Monitor     1
Name: count, dtype: int64

=== Customer frequency ===
customer_name
Alice      3
Bob        2
Charlie    2
Dave       1
Name: count, dtype: int64

In [455]:
# GroupBy — total per customer
print("=== Total spending per customer ===")
print(df.groupby(["customer_name"])["order_amount"].sum())
print(df.groupby(["customer_name"])["order_amount"].mean())
print(df.groupby(["customer_name"])["order_amount"].min())

=== Total spending per customer ===
customer_name
Alice      1479.97
Bob        1399.98
Charlie    1549.98
Dave         29.99
Name: order_amount, dtype: float64
customer_name
Alice      493.323333
Bob        699.990000
Charlie    774.990000
Dave        29.990000
Name: order_amount, dtype: float64
customer_name
Alice       79.99
Bob        699.99
Charlie    549.99
Dave        29.99
Name: order_amount, dtype: float64

In [458]:
# GroupBy — multiple aggregations
print("=== Customer summary ===")
customer_summary = df.groupby("customer_name")["order_amount"].agg(
    ["sum", "mean", "count", "min", "max"]
)
print(customer_summary)

=== Customer summary ===
                   sum        mean  count     min     max
customer_name
Alice          1479.97  493.323333      3   79.99  999.99
Bob            1399.98  699.990000      2  699.99  699.99
Charlie        1549.98  774.990000      2  549.99  999.99
Dave             29.99   29.990000      1   29.99   29.99

In [459]:
# GroupBy multiple columns with custom columns
print("=== Revenue by city ===")
city_summary = df.groupby("city")["order_amount"].agg(["sum", "count"])
city_summary.columns = ["total_revenue", "num_orders"]
print(city_summary)

=== Revenue by city ===
            total_revenue  num_orders
city
Chittagong         729.98           2
Dhaka             2649.96           4
Sylhet            1079.98           2

## 12. Hands-On Exercise: E-Commerce Analysis

Put it all together! Complete these tasks:

1. Filter orders where amount > ৳500
2. Add a "discount" column: 10% of order_amount
3. Add a "final_price" column: order_amount - discount
4. Sort by final_price descending
5. Group by customer — find total and average spending
6. Export the result

In [ ]:
# 🎯 YOUR TURN — Complete the exercise!

# Step 1: Filter expensive orders
expensive_orders = df[df["order_amount"] > 500]
print(f"Expensive orders: {len(expensive_orders)}")
print(expensive_orders[["customer_name", "product", "order_amount"]])

In [ ]:
# Step 2: Add discount column (10%)
expensive_orders = expensive_orders.copy()  # Avoid SettingWithCopyWarning
expensive_orders["discount"] = expensive_orders["order_amount"] * 0.10
print(expensive_orders[["product", "order_amount", "discount"]].head())

In [ ]:
# Step 3: Add final_price column
expensive_orders["final_price"] = expensive_orders["order_amount"] - expensive_orders["discount"]
print(expensive_orders[["product", "order_amount", "discount", "final_price"]].head())

In [ ]:
# Step 4: Sort by final_price descending
expensive_sorted = expensive_orders.sort_values("final_price", ascending=False).reset_index(drop=True)
print(expensive_sorted[["customer_name", "product", "final_price"]])

In [ ]:
# Step 5: Group by customer — total and average spending
customer_analysis = expensive_orders.groupby("customer_name")["final_price"].agg(
    ["sum", "mean", "count"]
)
customer_analysis.columns = ["total_spent", "avg_order", "num_orders"]
print("=== Customer Analysis ===")
print(customer_analysis)

In [ ]:
# Step 6: Export
expensive_sorted.to_csv("analysis_output.csv", index=False)
print("✅ Exported to analysis_output.csv!")

## 13. Best Practices Recap

✅ **Always explore first** — `head()`, `shape`, `info()`  
✅ **Use bracket notation** — `df["col"]` not `df.col`  
✅ **Chain operations** — `df.filter().sort_values().head()`  
✅ **Avoid loops** — use vectorized operations  
✅ **Save intermediate results** — export at each pipeline stage  
✅ **Name columns clearly** — `snake_case`, lowercase, no spaces